### ISSUE TITLE
Download Proposal Error

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#226]
When attempting to download a proposal I get the following error:

```
Internal Server Error: /proposals/3/
Traceback (most recent call last):
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/var/www/vhosts/rua_deploy/sup/src/core/decorators.py", line 54, in wrap
   return function(request, *args, **kwargs)
 File "/var/www/vhosts/rua_deploy/sup/src/core/views.py", line 928, in view_proposal
   path = create_proposal_form(proposal)
 File "/var/www/vhosts/rua_deploy/sup/src/core/views.py", line 944, in create_proposal_form
   relations = models.ProposalFormElementsRelationship.objects.filter(form=proposal.review_form)
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
   return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
   return self._filter_or_exclude(False, *args, **kwargs)
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
   clone.query.add_q(Q(*args, **kwargs))
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1309, in add_q
   clause, require_inner = self._add_q(where_part, self.used_aliases)
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1337, in _add_q
   allow_joins=allow_joins, split_subq=split_subq,
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1178, in build_filter
   self.check_related_objects(field, value, opts)
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1073, in check_related_objects
   self.check_query_object_type(value, opts)
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1057, in check_query_object_type
   (value, opts.object_name))
ValueError: Cannot query "rua_review_form": Must be "ProposalForm" instance.
```

Was this tested before it was pushed to the repo?

**Comment by IoannisCleary** [comment]
I tested it before I committed it and the error didn't appear. Now it does
