### ISSUE TITLE
Python manage steps fail

### ISSUE THREAD

**Issue by bartzon** [ubiquitypress/rua#292]
Running python manage returns an error: ImportError: No module settings. 
I'm suspecting this package is missing from the requirements?
See below for the details.

Running python via homebrew on OS X:
```
$ python --version
Python 2.7.11
```

```
$ cd src
$ python manage.py syncdb                                                                                               
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/bartz/.virtualenvs/rua/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/bartz/.virtualenvs/rua/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/Users/bartz/.virtualenvs/rua/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/Users/bartz/.virtualenvs/rua/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/bartz/.virtualenvs/rua/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings
```

Same error for the migrate and runserver command.

**Comment by ajrbyers** [comment]
@babolili it looks like I've missed a step off of the quick guide. In the Core director there is a file called dev_settings.py, you'll need to copy it and then update it.

cp dev_settings.py settings.py

Once you've updated the settings file (for example to connect to your local DB) it should be fine!

**Comment by bartzon** [comment]
That worked! Another small typo though:

```
python manage.py loaddata core/fixtures/settinggroup.json
```
should be
```
python manage.py loaddata core/fixtures/settinggroups.json
```
